### ISSUE TITLE
Prototipo UI Design

### ISSUE THREAD

**Issue by DavidEliass** [CarlosZiegler/jobforme#10]
Boa Tarde,segue abaixo um modelo de layout para o JobForme.

![HOMELayout](https://user-images.githubusercontent.com/32375682/82596410-a33b2100-9b7d-11ea-8e87-bd81fea51efd.png)

**Fico a disposição para discussão e ajudar no projeto.**

**Atenciosamente David Elias.**

**Comment by CarlosZiegler** [comment]
Achei massa, simples moderno e objetivo. Porem da uma olhada que fiz uma alteracao no site, agora pode-se cadastrar e exibir vagas.

Obs: Eu curti muito a imagem do Lotties que esta no site hoje, voce acha que consegue encaixar ela?

**Comment by CenourinhaBR** [comment]
Pode deixar vou tentar em caixa e realizar alterações.

**Comment by CarlosZiegler** [comment]
> Pode deixar vou tentar em caixa e realizar alterações.

Tranquilo, outra coisa, tem uma pull request aberta #12 . Foi implementado algumas modificacoes, nao foi aprovada, comente com ele para voces trocarem uma ideia sobre Layout. Seria bacana trabalhar assim. O que voce acha?

**Comment by CenourinhaBR** [comment]
> > Pode deixar vou tentar em caixa e realizar alterações.
> 
> Tranquilo, outra coisa, tem uma pull request aberta #12 . Foi implementado algumas modificacoes, nao foi aprovada, comente com ele para voces trocarem uma ideia sobre Layout. Seria bacana trabalhar assim. O que voce acha?

Acho legal vou conversa assim, fica até mais facil.

**Comment by CenourinhaBR** [comment]
### **Adicionados Novas Telas e Ajustes**
![Add PerfilLayout](https://user-images.githubusercontent.com/32375682/82622625-af8ea080-9bb4-11ea-8e65-ac984015138e.png)
![Email](https://user-images.githubusercontent.com/32375682/82622627-b0273700-9bb4-11ea-9319-e69700b04b64.png)

**Comment by CarlosZiegler** [comment]
Show de bola... Esperando para ver os novos design

**Comment by CenourinhaBR** [comment]
Boa Tarde, eu e o @IdenilsonSantos fizemos novos protótipos para o site, contamos com o seu feedback.

![Login (1)](https://user-images.githubusercontent.com/32375682/83050792-7080a500-a023-11ea-862d-14971ef6d851.png)

![Dashboard](https://user-images.githubusercontent.com/32375682/83050809-77a7b300-a023-11ea-8783-4c3c2c912f0c.png)

![Register](https://user-images.githubusercontent.com/32375682/83050818-7b3b3a00-a023-11ea-9e7c-583efd7ca369.png)

![Vagas](https://user-images.githubusercontent.com/32375682/83050833-7ecec100-a023-11ea-891a-fcb34305d2d2.png)

![HOME (6)](https://user-images.githubusercontent.com/32375682/83050841-80988480-a023-11ea-9249-e705dafcb5f9.png)
