### ISSUE TITLE
Organização

### ISSUE THREAD

**Issue by IdenilsonSantos** [CarlosZiegler/jobforme#21]
Olá,
Me surgiu uma dúvida, já existe algum tipo de organização dos times e o que começar de imediato ?

**Comment by CarlosZiegler** [comment]
Ainda nao, mas podemos formalizar isso. Voce consegue ver na aba projeto um Kanban que eu fiz?

**Comment by rafaelmaiach** [comment]
Olá @CarlosZiegler consigo ver.
Se estiverem precisando de mais gente pra participar do projeto, será um prazer ajudar.

**Comment by CarlosZiegler** [comment]
Ola Rafael, tudo bem ? Então como o projeto é open-source,  sempre tem lugar para mais um. Hoje ou amanhã vou fazer o merge de uma pr , que provavelmente pessoal vaibter que atualizar seus forks, por que passei de spa com react para usar a Nextjs.

**Comment by rafaelmaiach** [comment]
Opa perfeito! Vou esperar esse PR entrar então. Isso vai mudar bastante a estrutura, então evita retrabalho se eu mexer em algo em cima do SPA.

**Comment by IdenilsonSantos** [comment]
@rafaelmaiach no aguardo também ;)

**Comment by Tava1** [comment]
Olá, venho por meio de um post que o @rafaelmaiach publicou no Linkedin. Dei uma olhada no projeto e gostei bastante. Vi que o pessoal já mandou algumas ideias de UIs, gostaria de poder ajudar bastante na codificação quando tiver algo formalizado.

**Comment by rafaelmaiach** [comment]
@Tava1 da uma olhada nessa Issue https://github.com/CarlosZiegler/jobforme/issues/31 tem o link do Discord do projeto

**Comment by IdenilsonSantos** [comment]
@Tava1 seja bem vindo, sua ajuda será de grande valia. Temos o Discord do projeto https://discord.gg/JmQBVH 
abrc...

**Comment by CarlosZiegler** [comment]
Ola pessoal, desculpe a demora, esta bem corrido aqui para mim mas terminando a integracao com Firebase que o @stenzel começou e logo subo esse pr para voces verem e continuarem as implementacoes. Ate final de semana nao passa OK?

**Comment by Tava1** [comment]
@rafaelmaiach @IdenilsonSantos Beleza, muito obrigado!

**Comment by CarlosZiegler** [comment]
Aqui o Link atualizado, confere ai se esta correto. ->https://discord.gg/k58qY4
