### ISSUE TITLE
README-UPDATE

### ISSUE THREAD

**Issue by CarlosZiegler** [CarlosZiegler/jobforme#26]
@lucas-felinto adiciona o @rafaelmaiach como contribuidor assim como @IdenilsonSantos @CenourinhaBR @lucaspinheirogit que estão contribuindo no projeto. Ai manda uma PR. Tambem precisa atualizar o passo a passo, adicionar o passo a passo para trabalhar localmente. 

-'yarn dev' -> nextjs local
- 'yarn fix' -> eslint

Acho que é isso. Se estiver esquecendo alguem ou alguma coisa comenta ai..

**Comment by rafaelmaiach** [comment]
Obrigado pelo reconhecimento @CarlosZiegler ! 
Vou ajudar no que for possível e necessário pra que esse projeto fique cada vez mais interessante!
