### ISSUE TITLE
Implementação de cadastro pelo LinkedIn e ou GitHub.

### ISSUE THREAD

**Issue by benits** [CarlosZiegler/jobforme#29]
O que vocês acham de deixar o processo para cadastros mais facil e rápido, apenas com a pessoa vinculando LinkedIn e ou GitHub. 

Eu posso ajudar com isso!!

**Comment by CarlosZiegler** [comment]
Acho uma otima idéia, estamos querendo usar o firebase para auth e cadastros. Assim podemos ampliar para facebook, google, etc... O que voce acha?

**Comment by benits** [comment]
acho interessante, eu tenho algumas ideias para ajudar no projeto. como consigo seu contato?

**Comment by CarlosZiegler** [comment]
Ola tudo bem? Pode me achar no Linkedin.

Em qui, 28 de mai de 2020 21:46, Matheus Benites <notifications@github.com>
escreveu:
