### ISSUE TITLE
NextJS

### ISSUE THREAD

**Issue by ribeiroevandro** [CarlosZiegler/jobforme#3]
Notei que o site está feito com o ReactJS apenas, que não oferece SEO, algo importante nesse tipo de projeto, o que acham de migrar para o NextJS? Posso auxiliar nessa conversão.

**Comment by CarlosZiegler** [comment]
Ola @ribeiroevandro, Entao o projeto agora era um MVP, o que eu fiz:

Frontend React -> para mostrar os dados
Google Forms -> Coletar Dados
Google Spreadsheet -> Para guardar as informacoes

Mudando um pouco a url do google consegue chegar a um endpoint da tabela, ai fiz um fetch dos dados. Assim nao precisei desenvolver um Backend. O que agora seria uma boa necessidade.

Eu tenho ele hospedado no Vercel, que usa NextJs. Seria Bacana implementar-mos algo la sim.

**Comment by ribeiroevandro** [comment]
@CarlosZiegler se quiser, posso rascunhar algo e já fazer conexão com uma base no Firebase, o que acha?

**Comment by CarlosZiegler** [comment]
Bora lá faz um fork e implementa ele depois manda teu fork para eu dar uma olhada...

**Comment by ribeiroevandro** [comment]
@CarlosZiegler irado, farei agora... Usarei uma base minha no Firebase para testes, mas deixei instruções de como replicar e também já farei testes de carga, para que sejam preenchidos os dados que já possuem na base. o/

**Comment by CarlosZiegler** [comment]
Entao, a minha base de dados ainda é a tabela do Google, ai vamos ter que resolver algumas questões de migração... por exemplo a pessoa depois de implantado o sistema de firebase fará login na aplicação,  e precisamos fornecer isso para os dados ja inclusos.

**Comment by CarlosZiegler** [comment]
Estou fechando essa ISSUE pois o projeto ja foi migrado para NextJS
