### ISSUE TITLE
Discord

### ISSUE THREAD

**Issue by CarlosZiegler** [CarlosZiegler/jobforme#31]
Ola, criei um grupo no Discord, caso queiram discutir implementacoes acho que seria bacana, o que voces acham?

https://discord.gg/JmQBVH

**Comment by rafaelmaiach** [comment]
Ótimo Carlos! Acabei de entrar!

**Comment by Tava1** [comment]
Este convite para o discord venceu, tem que criar outro. Tem uma opção que é possível configurar a validade.

**Comment by RanderGabriel** [comment]
Tentei acessar pelo link também e não consegui :/

**Comment by carlosstenzel** [comment]
https://discord.gg/J9Emuq
